site_dir: "site"
site_name: "socx-cli"
site_url: "https://sagikimhi.dev/socx-cli/"
site_description: "System on chip verification and tooling infrastructure."

repo_name: "sagikimhi/socx-cli"
repo_url: "https://github.com/sagikimhi/socx-cli"
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Sagi Kimhi

watch:
  - mkdocs.yml
  - README.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - src/socx
  - src/socx_tui
  - src/socx_plugins

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
      - Overview: index.md
      - Changelog: home/changelog.md
      - Credits: home/credits.md
      - License: home/license.md
  - Quick Start: home/quickstart.md
  - User Guide:
      - CLI Tour: user-guide/cli.md
      - Configuration: user-guide/configuration.md
      - Regression Automation: user-guide/regression.md
      - Plugin Development: user-guide/plugins.md
  - Reference:
      - Configuration: reference/configuration.md
      - API: reference/api.md
  - Conepts:
      - Plugins: concepts/plugins.md
  - Development:
      - Contributing: development/contributing.md
      - Code of Conduct: development/code_of_conduct.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - sh
    - zsh
    - bash
    - tcsh
    - yaml
    - python
    - verilog
    - systemverilog
  features:
    - toc.follow
    - navigation.top
    - navigation.path
    - navigation.prune
    - navigation.header
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  custom_dir: docs/.overrides
  extra_css:
    - css/material.css
    - css/mkdocstrings.css
  extra_javascript:
    - js/mathjax.js
    - js/feedback.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  # Python Markdown
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: On this page
      permalink: true
  # Python Markdown Extensions
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      auto_title: false
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption

plugins:
  - tags
  - offline
  - search
  - social
  - macros
  - autorefs
  - section-index
  - markdown-exec
  - mike:
      alias_type: copy
  - git-revision-date-localized:
      type: date
      strict: false
      fallback_to_build_date: true
  - llmstxt:
      full_output: llms-full.txt
      sections:
        Usage:
          - index.md
        API:
          - reference/api.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            summary: true
            backlinks: tree
            filters: ["!^_"]
            heading_level: 1
            show_bases: true
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            signature_crossrefs: true
            show_symbol_type_toc: true
            show_if_no_docstring: true
            show_symbol_type_heading: true
            show_signature_annotations: true
            inherited_members: true
            separate_signature: true
            merge_init_into_class: true
            docstring_section_style: list
            docstring_options:
              ignore_init_summary: true
          inventories:
            - https://docs.python.org/3/objects.inv

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sagikimhi
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/socx-cli/community
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/socx-cli/

  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Let us know how we can improve this page.
