[plugins.regression]
name = "rgr"
entry = "@entrypoint @format socx_plugins.rgr"

[plugins.config]
name = "config"
entry = "@entrypoint @format socx_plugins.config"

[plugins.example]
name = "example"
entry = "@entrypoint @format socx_plugins.example"

[plugins.convert]
name = "convert"
entry = "@entrypoint @format socx_plugins.convert"
