[plugins.rgr]
name = "rgr"
entry = "@entrypoint socx_plugins.rgr"

[plugins.env]
name = "env"
entry = "@entrypoint socx_plugins.env"

[plugins.config]
name = "config"
entry = "@entrypoint socx_plugins.config"

[plugins.example]
name = "example"
entry = "@entrypoint socx_plugins.example"

[plugins.convert]
name = "convert"
entry = "@entrypoint socx_plugins.convert"
