[plugins.rgr]
name = "rgr"
entry = "@entrypoint socx_plugins.rgr"

[plugins.git]
name = "git"
entry = "@entrypoint socx_plugins.git.cli"

[plugins.config]
name = "config"
entry = "@entrypoint socx_plugins.config"

[plugins.example]
name = "example"
entry = "@entrypoint socx_plugins.example"

[plugins.convert]
name = "convert"
entry = "@entrypoint socx_plugins.convert"

[plugins.ui]
name = "ui"
entry = "@entrypoint socx_plugins.ui"
commands = []

