dynaconf_include:
  - "@jinja {{this.paths.app_config_dir}}/rich_click.yaml"
  - "@jinja {{this.paths.app_config_dir}}/cli.yaml"
  - "@jinja {{this.paths.app_config_dir}}/console.yaml"
  - "@jinja {{this.paths.app_config_dir}}/plugins.yaml"
  - "@jinja {{this.paths.app_config_dir}}/git.yaml"
  - "@jinja {{this.paths.app_config_dir}}/regression.yaml"
