bump = "auto"
convention = "angular"
in-place = true
output = "CHANGELOG.md"
parse-refs = true
parse-trailers = true
sections = ["build", "deps", "feat", "fix", "refactor", "hotfix", "bugfix", "docs",]
template = "keepachangelog"
versioning = "pep440"
